# Generated by Django 3.0.7 on 2020-06-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peringkat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=1)),
                ('pialaEmas', models.IntegerField()),
                ('pialaPerak', models.IntegerField()),
                ('pialaTembaga', models.IntegerField()),
            ],
        ),
    ]
