# Generated by Django 3.0.7 on 2020-06-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peringkat',
            new_name='Player',
        ),
    ]
