# Generated by Django 3.0.7 on 2020-06-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200614_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
